/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package code;


import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IT Supporter
 */
public class Hoadon extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    String chiTiet="";
    DefaultTableModel model;
    public static List<ThongTinHoaDon> thongTinDatPhongs;
    public Hoadon() {
        initComponents();
        load();
    }
    
    private void load(){
        model= (DefaultTableModel) tbTTDPAdmin.getModel();
        model.setNumRows(0);
        thongTinDatPhongs= FileController.layTatCaThongTinDatPhong();
        for(ThongTinHoaDon tt: thongTinDatPhongs){
            model.addRow(new Object[]{
                tt.getMaHD(), tt.getTenKH(), tt.getSdt(), tt.getdouong(), tt.getdoan(), tt.getSoTienDuKien()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTTDPAdmin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtMaHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edtTenKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DoUong = new javax.swing.JTextField();
        DoAn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edtSoTienDuKien = new javax.swing.JTextField();
        BtnUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách hóa đơn");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách thông tin hóa đơn");

        tbTTDPAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Ten KH", "SDT", "Đồ uống", "Đồ ăn kèm", "Tổng tiền thanh toán"
            }
        ));
        tbTTDPAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTTDPAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTTDPAdmin);

        jLabel2.setText("Sửa thông tin");

        jLabel3.setText("Ma HD");

        jLabel4.setText("Ten KH");

        jLabel5.setText("SDT");

        jLabel6.setText("Do uong");

        jLabel7.setText("Do an kem");

        jLabel8.setText("Tong tien thanh toan");

        edtSoTienDuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSoTienDuKienActionPerformed(evt);
            }
        });

        BtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Edit.png"))); // NOI18N
        BtnUpdate.setText("Sửa");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Chọn 1 dòng trong bảng để sửa thông tin");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Log out.png"))); // NOI18N
        jButton2.setText("Quay lai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Delete.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Accept.png"))); // NOI18N
        jButton4.setText("Xem chi tiết");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Add.png"))); // NOI18N
        BtnAdd.setText("Thêm");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(DoUong))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DoAn, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(edtTenKH))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(64, 64, 64)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(edtSoTienDuKien, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(edtSDT))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(45, 45, 45)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(edtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(edtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(edtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(edtSoTienDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtSoTienDuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSoTienDuKienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSoTienDuKienActionPerformed

    private void tbTTDPAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTTDPAdminMouseClicked
        int row= tbTTDPAdmin.getSelectedRow();
        String maHD= (String) tbTTDPAdmin.getValueAt(row, 0);
        String tenKH= (String) tbTTDPAdmin.getValueAt(row, 1);
        String sdt= (String) tbTTDPAdmin.getValueAt(row, 2);
        String ngayDat= (String) tbTTDPAdmin.getValueAt(row, 3);
        String ngayTra= (String) tbTTDPAdmin.getValueAt(row, 4);
        String tienDuKien= (String) tbTTDPAdmin.getValueAt(row, 5);
        
        chiTiet= maHD+","+ tenKH+","+sdt+","+ngayDat+","+ngayTra+","+tienDuKien;
        
        edtMaHD.setText(maHD);
        edtTenKH.setText(tenKH);
        edtSDT.setText(sdt);
        DoUong.setText(ngayDat);
        DoAn.setText(ngayTra);
        edtSoTienDuKien.setText(tienDuKien);
    }//GEN-LAST:event_tbTTDPAdminMouseClicked

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try{
            Integer.parseInt(edtSoTienDuKien.getText());
            try {
                String maHD= edtMaHD.getText().trim();
                String tenKH= edtTenKH.getText().trim();
                String sdt= edtSDT.getText().trim();
                String ngayDat= DoUong.getText().trim();
                String ngayTra= DoAn.getText().trim();
                String tienDuKien= edtSoTienDuKien.getText().trim();

                int row = tbTTDPAdmin.getSelectedRow();
                thongTinDatPhongs.get(row).setMaHD(maHD);
                thongTinDatPhongs.get(row).setTenKH(tenKH);
                thongTinDatPhongs.get(row).setSdt(sdt);
                thongTinDatPhongs.get(row).setdouong(ngayDat);
                thongTinDatPhongs.get(row).setdoan(ngayTra);
                thongTinDatPhongs.get(row).setSoTienDuKien(tienDuKien);
                FileController.UpdateHoaDon(thongTinDatPhongs);

                //update tren giao dien
                model.setValueAt(maHD, row, 0);
                model.setValueAt(tenKH, row, 1);
                model.setValueAt(sdt, row, 2);
                model.setValueAt(ngayDat, row, 3);
                model.setValueAt(ngayTra, row, 4);
                model.setValueAt(tienDuKien, row, 5);


            } catch (Exception e) {
                   JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập lương là kiểu số nguyên");
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         this.setVisible(false);
       TrangChu ct= new TrangChu(); ct.setVisible(true);
       ct.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int row= tbTTDPAdmin.getSelectedRow();
        thongTinDatPhongs.remove(row);
        model.removeRow(row);
        FileController.DeleteHoaDon();
        FileController.UpdateHoaDon(thongTinDatPhongs);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
       Chitiethoadon hd= new Chitiethoadon(); 
       hd.setStr(chiTiet);
       hd.setVisible(true);
       hd.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private boolean checkDL(){
        String mess = "";
        if(edtMaHD.getText().equals("")||edtTenKH.getText().equals("")||edtSDT.getText().equals("")||DoUong.getText().equals("")||DoAn.getText().equals("")||edtSoTienDuKien.getText().equals("")){
           mess +="\n Bạn cần phải nhập đầy đủ thông tin";
        }
        Pattern checkMaNV = Pattern.compile("^HD[0-9]+$");
        if(!checkMaNV.matcher(edtMaHD.getText()).find()){
            mess +="\n Mã hóa đơn nhập vào cần có dạng HD theo sau bởi các kí tự số";
        }
        Pattern checkSDT = Pattern.compile("^0[1-9][0-9]{8}$");
        if(!checkSDT.matcher(edtSDT.getText()).find()){
            mess +="\n Số điện thoại bạn nhập vào không hợp lệ";
        }
        
        if(!"".equals(mess)){
            JOptionPane.showMessageDialog(rootPane, mess);
            return false;
        }
        return true;
        
    }
    
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try{
            Integer.parseInt(edtSoTienDuKien.getText());
            try{
                if(checkDL()){
                    boolean isNV=false;
                    for(ThongTinHoaDon hd:thongTinDatPhongs)
                        if(hd.getMaHD().equals(edtMaHD.getText())) {
                            isNV=true;
                            break;
                        }
                    if(isNV){
                        JOptionPane.showMessageDialog(rootPane, "Hóa đơn đã tồn tại");
                    }
                    else{
                        String result = edtMaHD.getText() + ";" + edtTenKH.getText() + ";" + edtSDT.getText() + ";" + DoUong.getText() + ";" + DoAn.getText() + ";" + edtSoTienDuKien.getText()+"\n";
                        FileController.AddNew(result, "thongtindatphong.txt");

                        // reset lai o textbox
                        edtMaHD.setText("");
                        edtTenKH.setText("");
                        edtSDT.setText("");
                        DoUong.setText("");
                        DoAn.setText("");
                        edtSoTienDuKien.setText("");

                        load();
                    }
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Có lỗi khi thêm: "+ex.toString());
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập lương là kiểu số nguyên");
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Hoadon hd = new Hoadon();
        
                    hd.setLocationRelativeTo(null);
                    hd.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField DoAn;
    private javax.swing.JTextField DoUong;
    private javax.swing.JTextField edtMaHD;
    private javax.swing.JTextField edtSDT;
    private javax.swing.JTextField edtSoTienDuKien;
    private javax.swing.JTextField edtTenKH;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTTDPAdmin;
    // End of variables declaration//GEN-END:variables
}
