/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khanh Tran
 */
public class Quanlisanpham extends javax.swing.JFrame {

    /**
     * Creates new form Quanlisanpham
     */
    DefaultTableModel model;
    public static List<SanPham> DanhSachSanPham;
    public Quanlisanpham() {
        initComponents();
        load();
    }
    
    public void load(){
        model= (DefaultTableModel) TableSanPham.getModel();
        model.setNumRows(0);
        DanhSachSanPham = FileController.LayThongTinSanPham();
        for(SanPham tt: DanhSachSanPham){
            model.addRow(new Object[]{
                tt.getMaSP(), tt.getTenSP(), tt.getGiaTienM(), tt.getGiaTienL(), tt.getDonvi(), tt.getMota()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSanPham = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Masp = new javax.swing.JTextField();
        Tensp = new javax.swing.JTextField();
        GiatienM = new javax.swing.JTextField();
        Donvi = new javax.swing.JTextField();
        Mota = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        GiatienL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí sản phẩm");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Quản lí sản phẩm quán trà sữa");

        TableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá tiền loại M", "Giá tiền loại L", "Đơn vị", "Mô tả"
            }
        ));
        TableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClick(evt);
            }
        });
        jScrollPane1.setViewportView(TableSanPham);
        if (TableSanPham.getColumnModel().getColumnCount() > 0) {
            TableSanPham.getColumnModel().getColumn(0).setPreferredWidth(20);
            TableSanPham.getColumnModel().getColumn(2).setPreferredWidth(80);
            TableSanPham.getColumnModel().getColumn(3).setPreferredWidth(80);
        }

        jLabel2.setText("Mã sản phẩm :");

        jLabel3.setText("Tên sản phẩm :");

        jLabel4.setText("Giá tiền loại M:");

        jLabel5.setText("Đơn vị sản phẩm :");

        jLabel6.setText("Mô tả :");

        Masp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaspActionPerformed(evt);
            }
        });

        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Add.png"))); // NOI18N
        BtnAdd.setText("Thêm ");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Edit.png"))); // NOI18N
        BtnUpdate.setText("Sửa ");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Delete.png"))); // NOI18N
        BtnDelete.setText("Xóa");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Log out.png"))); // NOI18N
        jButton4.setText("Quay lại");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Giá tiền loại L:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Donvi)
                            .addComponent(Masp)
                            .addComponent(Tensp, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(BtnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GiatienM, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Mota)
                            .addComponent(GiatienL, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Masp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(GiatienM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(GiatienL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Mota, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Donvi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaspActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         this.setVisible(false);
       TrangChu ct= new TrangChu(); ct.setVisible(true);
       ct.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void MouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClick
        int row= TableSanPham.getSelectedRow();
        String id= (String) TableSanPham.getValueAt(row, 0);
        String tensp = (String) TableSanPham.getValueAt(row, 1);
        String giatienM = (String) TableSanPham.getValueAt(row, 2);
        String giatienL = (String) TableSanPham.getValueAt(row, 3);
        String donvi = (String) TableSanPham.getValueAt(row, 4);
        String mota = (String) TableSanPham.getValueAt(row, 5);
        
        Masp.setText(id);
        Tensp.setText(tensp);
        GiatienM.setText(giatienM);
        GiatienL.setText(giatienL);
        Donvi.setText(donvi);
        Mota.setText(mota);
    }//GEN-LAST:event_MouseClick

    private boolean checkDL(){
        String mess = "";
        if(Masp.getText().equals("")||Tensp.getText().equals("")||GiatienM.getText().equals("")||GiatienL.getText().equals("")||Donvi.getText().equals("")||Mota.getText().equals("")){
           mess +="\n Bạn cần phải nhập đầy đủ thông tin";
        }
        Pattern checkMaNV = Pattern.compile("^MH[0-9]+$");
        if(!checkMaNV.matcher(Masp.getText()).find()){
            mess +="\n Mã nhân viên nhập vào cần có dạng MH theo sau bởi các kí tự số";
        }

        if(!"".equals(mess)){
            JOptionPane.showMessageDialog(rootPane, mess);
            return false;
        }
        return true;
        
    }
    
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try{
            if(checkDL()){
                boolean isNV=false;
                for(SanPham nv:DanhSachSanPham)
                    if(nv.getMaSP().equals(Masp.getText())) {
                        isNV=true;
                        break;
                    }
                if(isNV){
                    JOptionPane.showMessageDialog(rootPane, "Sản phẩm đã tồn tại");
                }
                else{
                    String result = "\n"+Masp.getText() + ";" + Tensp.getText() + ";" + GiatienM.getText() + ";" + GiatienL.getText() + ";" + Donvi.getText() + ";" + Mota.getText();
                    FileController.AddNew(result, "SanPham.txt");
                    DanhSachSanPham.add(new SanPham(Masp.getText(), Tensp.getText(), GiatienM.getText(), GiatienL.getText(), Donvi.getText(), Mota.getText()));
                    
                    // reset lai o textbox
                   
                    
                    model.addRow(new Object[]{
                            Masp.getText() , Tensp.getText() , GiatienM.getText(), GiatienL.getText(), Donvi.getText() , Mota.getText()
                        });
                    
//                    load();

                    Masp.setText("");
                    Tensp.setText("");
                    GiatienM.setText("");
                    GiatienL.setText("");
                    Donvi.setText("");
                    Mota.setText("");
                }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Có lỗi khi thêm: "+ex.toString());
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try {
            String masp= Masp.getText().trim();
            String tensp= Tensp.getText().trim();
            String gtM= GiatienM.getText().trim();
            String gtL= GiatienL.getText().trim();
            String dv= Donvi.getText().trim();
            String mt= Mota.getText().trim();
            
            int row = TableSanPham.getSelectedRow();
            DanhSachSanPham.get(row).setMaSP(masp);
            DanhSachSanPham.get(row).setTenSP(tensp);
            DanhSachSanPham.get(row).setGiaTienM(gtM);
            DanhSachSanPham.get(row).setGiaTienL(gtL);
            DanhSachSanPham.get(row).setDonvi(dv);
            DanhSachSanPham.get(row).setMota(mt);
            
            FileController.UpdateSanPham(DanhSachSanPham);
            
            //update tren giao dien
            model.setValueAt(masp, row, 0);
            model.setValueAt(tensp, row, 1);
            model.setValueAt(gtM, row, 2);
            model.setValueAt(gtL, row, 3);
            model.setValueAt(dv, row, 4);
            model.setValueAt(mt, row, 5);
            
            // reset lai o textbox
            Masp.setText("");
            Tensp.setText("");
            GiatienM.setText("");
            GiatienL.setText("");
            Donvi.setText("");
            Mota.setText("");
        } catch (Exception e) {
               JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int mess = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa ?");
        if(mess==JOptionPane.YES_OPTION){
            int row= TableSanPham.getSelectedRow();
            DanhSachSanPham.remove(row);
            model.removeRow(row);
            
            FileController.DeleteSanPham();
            FileController.UpdateSanPham(DanhSachSanPham);
            
            // reset lai o textbox
            Masp.setText("");
            Tensp.setText("");
            GiatienM.setText("");
            GiatienL.setText("");
            Donvi.setText("");
            Mota.setText("");
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlisanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlisanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlisanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlisanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  Quanlisanpham q = new Quanlisanpham();
        
                    q.setLocationRelativeTo(null);
                    q.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField Donvi;
    private javax.swing.JTextField GiatienL;
    private javax.swing.JTextField GiatienM;
    private javax.swing.JTextField Masp;
    private javax.swing.JTextField Mota;
    private javax.swing.JTable TableSanPham;
    private javax.swing.JTextField Tensp;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
