/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Khanh Tran
 */
public class Quanlinhanvien extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    DefaultTableModel model;
    public static List<NguoiDung> DanhSachNhanVien;
    public Quanlinhanvien() {
        initComponents();
        load();
    }
    
    public void load(){
        model= (DefaultTableModel) TableNhanVien.getModel();
        model.setNumRows(0);
        DanhSachNhanVien = FileController.LayThonTinNhanVien();
        for(NguoiDung tt: DanhSachNhanVien){
            model.addRow(new Object[]{
                tt.getMaNhanVien(), tt.getTenNhanVien(), tt.getSdt(),tt.getSoNgayLuong()+"", tt.getChucVu()+"", tt.getLuong()+""
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BtnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Hoten = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Sdt = new javax.swing.JTextField();
        Luong = new javax.swing.JTextField();
        Songayluong = new javax.swing.JTextField();
        Chucvu = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí nhân viên ");

        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Số điện thoại", "Số ngày lương", "Chức vụ", "Tiền lương"
            }
        ));
        TableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClick(evt);
            }
        });
        jScrollPane2.setViewportView(TableNhanVien);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách quản lí nhân viên quán trà sữa ");

        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Tên nhân viên");

        BtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Add.png"))); // NOI18N
        BtnAdd.setText("Thêm ");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        jLabel4.setText("Số điện thoại");

        BtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Edit.png"))); // NOI18N
        BtnUpdate.setText("Sửa");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        jLabel5.setText("Số ngày lương");

        BtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Delete.png"))); // NOI18N
        BtnDelete.setText("Xóa");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        jLabel6.setText("Lương");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        jLabel7.setText("Chức vụ");

        Luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuongActionPerformed(evt);
            }
        });

        Songayluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SongayluongActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Log out.png"))); // NOI18N
        jButton4.setText("Quay lại");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Chucvu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Songayluong)
                            .addComponent(Hoten)
                            .addComponent(Luong, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Songayluong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Luong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClick
        int row= TableNhanVien.getSelectedRow();
        String id= (String) TableNhanVien.getValueAt(row, 0);
        String hoten= (String) TableNhanVien.getValueAt(row, 1);
        String sdt= (String) TableNhanVien.getValueAt(row, 2);
        String songayluong= (String) TableNhanVien.getValueAt(row, 3);
        String chucvu= (String) TableNhanVien.getValueAt(row, 4);
        String luong= (String) TableNhanVien.getValueAt(row, 5);
        
        ID.setText(id);
        Hoten.setText(hoten);
        Sdt.setText(sdt);
        Songayluong.setText(songayluong);
        Chucvu.setText(chucvu);
        Luong.setText(luong);
    }//GEN-LAST:event_MouseClick

    private boolean checkDL(){
        String mess = "";
        if(ID.getText().equals("")||Hoten.getText().equals("")||Sdt.getText().equals("")||Songayluong.getText().equals("")||Chucvu.getText().equals("")||Luong.getText().equals("")){
           mess +="\n Bạn cần phải nhập đầy đủ thông tin";
        }
        Pattern checkMaNV = Pattern.compile("^NV[0-9]+$");
        if(!checkMaNV.matcher(ID.getText()).find()){
            mess +="\n Mã nhân viên nhập vào cần có dạng NV theo sau bởi các kí tự số";
        }
        Pattern checkSDT = Pattern.compile("^0[1-9][0-9]{8}$");
        if(!checkSDT.matcher(Sdt.getText()).find()){
            mess +="\n Số điện thoại bạn nhập vào không hợp lệ";
        }
        Pattern checkNgayLam = Pattern.compile("^\\d+$");
        if(!checkNgayLam.matcher(Songayluong.getText()).find()){
            mess +="\n Số ngày làm nhập vào phải là số nguyên";
        }
        else{
            int soNgayLam = Integer.parseInt(Songayluong.getText());
            if(soNgayLam<0||soNgayLam>30){
                mess += "\n Số ngày lương phải lớn hơn 0 và nhỏ hơn 30";
            }
        }
        if(!"".equals(mess)){
            JOptionPane.showMessageDialog(rootPane, mess);
            return false;
        }
        return true;
        
    }
    
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try{
            Integer.parseInt(Luong.getText());
            try{
                if(checkDL()){
                    boolean isNV=false;
                    for(NguoiDung nv:DanhSachNhanVien)
                        if(nv.getMaNhanVien().equals(ID.getText())) {
                            isNV=true;
                            break;
                        }
                    if(isNV){
                        JOptionPane.showMessageDialog(rootPane, "Nhân viên đã tồn tại");
                    }
                    else{
                        String result = ID.getText() + ";" + Hoten.getText() + ";" + Sdt.getText() + ";" + Chucvu.getText() + ";" + Songayluong.getText() + ";" + Luong.getText()+"\n";
                        FileController.AddNew(result, "NhanVien.txt");

                        // reset lai o textbox
                        ID.setText("");
                        Hoten.setText("");
                        Sdt.setText("");
                        Songayluong.setText("");
                        Chucvu.setText("");
                        Luong.setText("");

                        load();
                    }
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Có lỗi khi thêm: "+ex.toString());
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập lương là kiểu số nguyên");
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try{
            Integer.parseInt(Luong.getText());
            try {
                String id= ID.getText().trim();
                String hoten= Hoten.getText().trim();
                String sdt= Sdt.getText().trim();
                String songayluong= Songayluong.getText().trim();
                String chucvu= Chucvu.getText().trim();
                String luong= Luong.getText().trim();

                int row = TableNhanVien.getSelectedRow();
                DanhSachNhanVien.get(row).setMaNhanVien(id);
                DanhSachNhanVien.get(row).setTenNhanVien(hoten);
                DanhSachNhanVien.get(row).setSdt(sdt);
                DanhSachNhanVien.get(row).setSoNgayLuong(songayluong);
                DanhSachNhanVien.get(row).setChucVu(chucvu);
                DanhSachNhanVien.get(row).setLuong(luong);

                FileController.UpdateNhanVien(DanhSachNhanVien);

                //update tren giao dien
                model.setValueAt(id, row, 0);
                model.setValueAt(hoten, row, 1);
                model.setValueAt(sdt, row, 2);
                model.setValueAt(songayluong, row, 3);
                model.setValueAt(chucvu, row, 4);
                model.setValueAt(luong, row, 5);

                // reset lai o textbox
                ID.setText("");
                Hoten.setText("");
                Sdt.setText("");
                Songayluong.setText("");
                Chucvu.setText("");
                Luong.setText("");
            } catch (Exception e) {
                   JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập lương là kiểu số nguyên");
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int mess = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa ?");
        if(mess==JOptionPane.YES_OPTION){
            int row= TableNhanVien.getSelectedRow();
            DanhSachNhanVien.remove(row);
            model.removeRow(row);
            
            FileController.DeleteNhanVien();
            FileController.UpdateNhanVien(DanhSachNhanVien);
            
            // reset lai o textbox
            ID.setText("");
            Hoten.setText("");
            Sdt.setText("");
            Songayluong.setText("");
            Chucvu.setText("");
            Luong.setText("");
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void SongayluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SongayluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SongayluongActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangChu ct= new TrangChu(); ct.setVisible(true);
        ct.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void LuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlinhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlinhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlinhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlinhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Quanlinhanvien nv = new Quanlinhanvien();
        
                    nv.setLocationRelativeTo(null);
                    nv.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField Chucvu;
    private javax.swing.JTextField Hoten;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Luong;
    private javax.swing.JTextField Sdt;
    private javax.swing.JTextField Songayluong;
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
