/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Khanh Tran
 */
public class Thongtinban extends javax.swing.JFrame {

    /**
     * Creates new form Thongtinban
     */
    DefaultTableModel model;
    public static List<Ban> DanhSachBan;
    public Thongtinban() {
        initComponents();
        load();
    }
    
    public void load(){
        model= (DefaultTableModel) Ban.getModel();
        DanhSachBan = FileController.LayThongTinBan();
        for(Ban tt: DanhSachBan){
            String doan = "", douong = "", tongtien = "";
            if(!tt.getLoaiDoAn().equals("not"))
                doan = tt.getLoaiDoAn();
            if(!tt.getLoaiDoUong().equals("not"))
                douong = tt.getLoaiDoUong();
            if(!tt.getTongTien().equals("not"))
                tongtien = tt.getTongTien();
            model.addRow(new Object[]{
                tt.getTenBan(), tt.getTinhTrang(), tt.getSoKhach(), douong, doan, tongtien
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ban = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnUpdate = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        TenBan = new javax.swing.JTextField();
        SLKhach = new javax.swing.JTextField();
        DoUong = new javax.swing.JTextField();
        DoAn = new javax.swing.JTextField();
        TongTien = new javax.swing.JTextField();
        PanelStatus = new javax.swing.JPanel();
        Empty = new javax.swing.JRadioButton();
        NotEmpty = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông tin bàn");
        setFocusCycleRoot(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Thông tin bàn của quán");

        Ban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên bàn", "Tình trạng", "Số khách", "Loại đồ uống", "Loại đồ ăn", "Tổng thanh toán"
            }
        ));
        Ban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClick(evt);
            }
        });
        jScrollPane1.setViewportView(Ban);

        jLabel2.setText("Tên bàn");

        jLabel3.setText("Tình trạng");

        jLabel4.setText("Số khách");

        jLabel5.setText("Loại đồ uống");

        jLabel6.setText("Loại đồ ăn");

        jLabel7.setText("Tổng tiền");

        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Edit.png"))); // NOI18N
        BtnUpdate.setText("Sửa");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Log out.png"))); // NOI18N
        BtnBack.setText("Quay lai");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        buttonGroup1.add(Empty);
        Empty.setText("Trống");
        Empty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmptyActionPerformed(evt);
            }
        });

        buttonGroup1.add(NotEmpty);
        NotEmpty.setText("Có khách");
        NotEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotEmptyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelStatusLayout = new javax.swing.GroupLayout(PanelStatus);
        PanelStatus.setLayout(PanelStatusLayout);
        PanelStatusLayout.setHorizontalGroup(
            PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Empty, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NotEmpty)
                .addContainerGap())
        );
        PanelStatusLayout.setVerticalGroup(
            PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatusLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Empty)
                    .addComponent(NotEmpty))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SLKhach, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TenBan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DoUong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DoAn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(TenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SLKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(DoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(BtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkDL(){
        String mess = "";
        if(TenBan.getText().equals("")||Empty.getText().equals("")||NotEmpty.getText().equals("")||SLKhach.getText().equals("")){
           mess +="\n Bạn cần phải nhập đầy đủ thông tin";
        }
        
        if(!"".equals(mess)){
            JOptionPane.showMessageDialog(rootPane, mess);
            return false;
        }
        return true;
        
    }
    
    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
         this.setVisible(false);
        TrangChu ct= new TrangChu(); ct.setVisible(true);
        ct.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try{
            Integer.parseInt(SLKhach.getText());
            try {
                String id= TenBan.getText().trim();
                String tinhtrang= "";
                String sl= SLKhach.getText().trim();
                if(!Empty.isSelected())
                    tinhtrang = "Có khách";
                else {
                    tinhtrang = "Trống";
                }

                String douong= DoUong.getText().trim();
                if(douong.equals("")||douong.equals("Không"))
                    douong = "not";
                String doan= DoAn.getText().trim();
                if(doan.equals("")||doan.equals("Không"))
                    doan = "not";
                String tongtien= TongTien.getText().trim();
                if(tongtien.equals(""))
                    tongtien = "not";

                int row = Ban.getSelectedRow();
                DanhSachBan.get(row).setTenBan(id);
                DanhSachBan.get(row).setTinhTrang(tinhtrang);
                DanhSachBan.get(row).setSoKhach(sl);
                DanhSachBan.get(row).setLoaiDoUong(douong);
                DanhSachBan.get(row).setLoaiDoAn(doan);
                DanhSachBan.get(row).setTongTien(tongtien);


                FileController.UpdateBan(DanhSachBan);

                //update tren giao dien
                model.setValueAt(id, row, 0);
                model.setValueAt(tinhtrang, row, 1);
                model.setValueAt(sl, row, 2);
                if(douong.equals("not")||douong.equals("Không")){
                    douong = "";
                    model.setValueAt(douong, row, 3);
                }
                else
                    model.setValueAt(douong, row, 3);
                if(doan.equals("not")||doan.equals("Không")){
                    doan = "";
                    model.setValueAt(doan, row, 4);
                }
                else
                    model.setValueAt(doan, row, 4);

                if(tongtien.equals("not")||tongtien.equals("Không")){
                    tongtien = "";
                    model.setValueAt(tongtien, row, 5);
                }
                else
                    model.setValueAt(tongtien, row, 5);

                // reset lai o textbox
                TenBan.setText("");
                SLKhach.setText("");
                Empty.setSelected(false);
                NotEmpty.setSelected(false);
                DoUong.setText("");
                DoAn.setText("");
                TongTien.setText("");
            } catch (Exception e) {
                   JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Số lượng khách phải là số nguyên và không âm");
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void MouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClick
        int row= Ban.getSelectedRow();
        String tenban = (String) Ban.getValueAt(row, 0);
        String tinhtrang = (String) Ban.getValueAt(row, 1);
        String sokhach = (String) Ban.getValueAt(row, 2);
        String douong = (String) Ban.getValueAt(row, 3);
        String doan = (String) Ban.getValueAt(row, 4);
        String tongtien = (String) Ban.getValueAt(row, 5);
        
        TenBan.setText(tenban);
        if(tinhtrang.equals("Trống")){
            NotEmpty.setSelected(false);
            Empty.setSelected(true);
        }
        else{
            Empty.setSelected(false);
            NotEmpty.setSelected(true);
        }
        SLKhach.setText(sokhach);
        if(douong.equals(""))
            DoUong.setText("Không");
        else
            DoUong.setText(douong);
        if(doan.equals(""))
            DoAn.setText("Không");
        else
            DoAn.setText(doan);
        TongTien.setText(tongtien);
    }//GEN-LAST:event_MouseClick

    private void EmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmptyActionPerformed
        Empty.setSelected(true);
        NotEmpty.setSelected(false);
        if(!SLKhach.getText().equals("0"))
            SLKhach.setText("0");
        DoUong.setText("");
        DoAn.setText("");
        TongTien.setText("");
    }//GEN-LAST:event_EmptyActionPerformed

    private void NotEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotEmptyActionPerformed
        Empty.setSelected(false);
        NotEmpty.setSelected(true);
    }//GEN-LAST:event_NotEmptyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thongtinban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thongtinban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thongtinban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thongtinban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thongtinban().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ban;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField DoAn;
    private javax.swing.JTextField DoUong;
    private javax.swing.JRadioButton Empty;
    private javax.swing.JRadioButton NotEmpty;
    private javax.swing.JPanel PanelStatus;
    private javax.swing.JTextField SLKhach;
    private javax.swing.JTextField TenBan;
    private javax.swing.JTextField TongTien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
